package net.techcrunch.outflowPayment.reconciliation;

public enum ReconciliationIssueType {
    STALE_TRANSFER,
    COMPLETED_TRANSFER_WITHOUT_DEBIT,
    FAILED_TRANSFER_WITHOUT_REVERSAL,
    REVERSAL_PENDING_STALE,
    REFUND_SUCCESSFUL_WITHOUT_DEBIT,
    REFUND_FAILED_WITHOUT_REVERSAL,
    REFUND_REVERSAL_PENDING_STALE,
    EXTERNAL_STATEMENT_WITHOUT_TRANSFER,
    TRANSFER_AMOUNT_MISMATCH,
    TRANSFER_STATUS_MISMATCH
}
